# Site Settings
title: HCI2
description: ""
baseurl: "/inf4-hci-2"
url: ""
author: "Angus P, Chris C, Ben S, Karel K"
author_avatar: ""

maps_api_key: "AIzaSyAxOiZ92X6IXfk13WPTDa8VYt_GEBDZzqo"

theme_pink: "#d5006f"
theme_light_blue: "#0093bd"
theme_dark_blue: "#002e5f"
theme_red: "#d50032"
theme_dark_gray: "#252525"

# Main Navigation (Manual)
navigation:
 - text: Home
   url: /

# Build Settings
paginate: 3
paginate_path: "posts/page:num"
markdown: kramdown
permalink: pretty
highlighter: rouge
gems: [jekyll-paginate]
sass:
  style: compressed


# Addition content types
collections:
  timeline:
    output: false

